name: Branch name check

on: [ push, pull_request ]

jobs:
  check:
    name: Branch name rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: '^(?:feature|fix)(?:-\d{1,5})?(?:-[a-z]+)+$'
          allowed_prefixes: 'feature,fix'
          ignore: master,develop
          min_length: 9
          max_length: 34

