name: CI main dispatcher

on: [push, pull_request]

jobs:
  check:
    name: Branch name rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
            regex: '^(?:feature|stable|fix)(?:-\d{1,5})?: (?:[a-z]+ )*[a-z]+$'
            allowed_prefixes: 'feature,stable,fix'
            ignore: main,develop
            min_length: 8
            max_length: 34

